// Scene Targets
//  placeholder: use SceneObject with SceneTarget

st_width[1]=142; st_height[1]=58;
st_charx[1]=0; st_chary[1]=0;
st_so_uid[1]=4; st_scr_id[1]=1;
StrCpy(st_desc+(1*SO_MAX_DESC), "Garage Door");
StrCpy(st_scr_msg+(1*SO_MAX_SMSG),"You use the Gold Key on the\nGarage Door, and it opens.");

st_width[2]=142; st_height[2]=58;
st_charx[2]=0; st_chary[2]=0;
st_so_uid[2]=0; st_scr_id[2]=0;
StrCpy(st_desc+(2*SO_MAX_DESC), "Inside of Garage");
StrCpy(st_scr_msg+(2*SO_MAX_SMSG),"");

